pub mod analysis;
pub mod audio;
pub mod audio_file;
pub mod browse;
pub mod database;
pub mod demo;
pub mod dsp;
#[cfg(windows)]
mod exclusive;
pub mod history;
pub mod import;
pub mod integrations;
pub mod media;
pub mod model;
mod mp4_trim;
mod opus;
pub mod plugins;
pub mod query;
pub mod scan;
mod secrets;
pub mod sync;
