pub mod analysis;
pub mod audio;
pub mod audio_file;
pub mod browse;
pub mod cast;
pub mod crossfade;
pub mod cue;
pub mod database;
pub mod demo;
pub mod discord;
pub mod doctor;
pub mod dsp;
pub mod effects;
#[cfg(windows)]
mod exclusive;
pub mod formats;
pub mod history;
pub mod import;
pub mod instance;
pub mod integrations;
pub mod media;
pub mod model;
mod mp4_trim;
mod opus;
pub mod plugins;
pub mod query;
pub mod radio;
pub mod scan;
mod secrets;
pub mod stems;
pub mod sync;
pub mod update;
pub mod wrapped;
