name = "needle-site"
main = "worker.js"
compatibility_date = "2026-09-01"
workers_dev = false

[assets]
directory = "./public"
binding = "ASSETS"

[[r2_buckets]]
binding = "DOWNLOADS"
bucket_name = "needle-downloads"

[[r2_buckets]]
binding = "CRASHES"
bucket_name = "needle-crashes"

[[routes]]
pattern = "needle.nnx.fyi"
custom_domain = true
